packages:
  - "docs"
  - "infrastructure"
  - "landing"
  - "packages/*"
  - "packages/create-frac/templates/demo"
  - "packages/create-frac/templates/blank"
  - "examples/*"

allowBuilds:
  esbuild: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
