packages:
  - "docs"
  - "packages/frac"
  - "packages/create-frac"
  - "packages/usefractal"
  - "packages/create-frac/templates/blank"

allowBuilds:
  esbuild: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
